server:
  port: 8206
spring:
  application:
    name: service-orders
  profiles:
    active: dev
  #数据库连接
  datasource:
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yygh_order?characterEncoding=utf-8&useSSL=false
  #json全局格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  #redis配置
  redis:
    port: 6379
    database: 0
    host: 192.168.142.6
    timeout: 180000
  #日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
